spring:
  application:
    name: payment-service
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/orderflow_payments
    username: orderflow
    password: orderflow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/orderflow

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      payment-gateway:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
