spring:
  application:
    name: order-service
  profiles:
    default: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/orderflow_orders
    username: orderflow
    password: orderflow
  flyway:
    url: jdbc:postgresql://localhost:5433/orderflow_orders
    user: orderflow
    password: orderflow
  cloud:
    function:
      definition: paymentEvents;inventoryEvents
    stream:
      bindings:
        paymentEvents-in-0:
          destination: payments.events
          group: order-service
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        inventoryEvents-in-0:
          destination: inventory.events
          group: order-service
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          paymentEvents-in-0:
            consumer:
              enable-dlq: true
              dlq-name: order-service.payments.events.dlq
          inventoryEvents-in-0:
            consumer:
              enable-dlq: true
              dlq-name: order-service.inventory.events.dlq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/orderflow

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true