spring:
  application:
    name: order-service
  profiles:
    default: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/orderflow_orders
    username: orderflow
    password: orderflow
  flyway:
    url: jdbc:postgresql://localhost:5433/orderflow_orders
    user: orderflow
    password: orderflow
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/orderflow

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true